"""all models created

Revision ID: 071dfe5418c5
Revises: 
Create Date: 2023-02-01 15:56:18.364730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '071dfe5418c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise',
    sa.Column('exercise_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('muscle', sa.String(), nullable=False),
    sa.Column('equipment', sa.String(), nullable=False),
    sa.Column('directions', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('exercise_id')
    )
    op.create_table('workout',
    sa.Column('workout_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workout_plan', sa.JSON(), nullable=False),
    sa.Column('is_saved', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('workout_id')
    )
    op.create_table('workout_exercises',
    sa.Column('workout_id', sa.Integer(), nullable=True),
    sa.Column('exercise_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.exercise_id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.workout_id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_exercises')
    op.drop_table('workout')
    op.drop_table('exercise')
    # ### end Alembic commands ###
