"""created and imported all models

Revision ID: 45955d0e7695
Revises: 
Create Date: 2023-02-02 12:23:23.273369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45955d0e7695'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise',
    sa.Column('exercise_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('muscle', sa.String(), nullable=False),
    sa.Column('equipment', sa.String(), nullable=False),
    sa.Column('directions', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('exercise_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('workout',
    sa.Column('workout_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workout_plan', sa.JSON(), nullable=False),
    sa.Column('is_saved', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('workout_id')
    )
    op.create_table('users_workouts',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('workout_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.workout_id'], )
    )
    op.create_table('workout_exercises',
    sa.Column('workout_id', sa.Integer(), nullable=True),
    sa.Column('exercise_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.exercise_id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.workout_id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_exercises')
    op.drop_table('users_workouts')
    op.drop_table('workout')
    op.drop_table('user')
    op.drop_table('exercise')
    # ### end Alembic commands ###
