"""modified workout model

Revision ID: 8208087d3ef4
Revises: 0fa89f9f3d81
Create Date: 2023-01-31 19:22:07.270545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8208087d3ef4'
down_revision = '0fa89f9f3d81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_exercises',
    sa.Column('workout_id', sa.Integer(), nullable=True),
    sa.Column('exercise_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.exercise_id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.workout_id'], )
    )
    op.drop_table('user_workout')
    op.drop_table('workout_exercise')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.INTEGER(), server_default=sa.text("nextval('user_user_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name='user_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('workout_exercise',
    sa.Column('workout_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('exercise_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.exercise_id'], name='workout_exercise_exercise_id_fkey'),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.workout_id'], name='workout_exercise_workout_id_fkey'),
    sa.PrimaryKeyConstraint('workout_id', 'exercise_id', name='workout_exercise_pkey')
    )
    op.create_table('user_workout',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('workout_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name='user_workout_user_id_fkey'),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.workout_id'], name='user_workout_workout_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'workout_id', name='user_workout_pkey')
    )
    op.drop_table('workout_exercises')
    # ### end Alembic commands ###
